### ISSUE TITLE
Drupal version

### ISSUE THREAD

**Issue by gregoriopellegrino** [anthonylv/pyD2W#1]
Hi,
thanks for this script. I would suggest to add a flag to the command line to select the Drupal version. For example I saw on row 122 of file d2w.py that the version selected is only drupal 7 (tables = tables_d7) and I had to change the code to make it work.

**Comment by anthonylv** [comment]
Hi,

You're welcome and thanks for the feedback. I'm actually working on re-writing large parts of the code. My local version will automatically select the correct tables depending on the Drupal version it finds.

I'll push it up when I've finished with my current round of changes.
