### ISSUE TITLE
No database selected

### ISSUE THREAD

**Issue by gregoriopellegrino** [anthonylv/pyD2W#2]
Hi,
running the analyse action I've got some of these errors:

```
An exception occured when trying to run a query: No database selected
```

**Comment by gregoriopellegrino** [comment]
Solved changing line 42 of file database_interface.py.

From:

```
if not database:
```

To:

```
if database:
```

**Comment by anthonylv** [comment]
Thanks again. I've also extensively re-written database_interface.py over the last few days to make it more robust. Perhaps I pushed out this previous release a bit too early :-( Thanks again.
