### ISSUE TITLE
Accents in URLs

### ISSUE THREAD

**Issue by gregoriopellegrino** [anthonylv/pyD2W#3]
Drupal leaves accents in URLs, Wordpress doesn't support them.

I used this MySQL code to replace them:

```
REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE(  
REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE(  
REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE( REPLACE(  
acc_tag,
'ù','u'),'ú','u'),'û','u'),'ü','u'),'ý','y'),'ë','e'),'à','a'),'á','a'),'â','a'),'ã','a'), 
'ä','a'),'å','a'),'æ','a'),'ç','c'),'è','e'),'é','e'),'ê','e'),'ë','e'),'ì','i'),'í','i'), 
'î','i'),'ï','i'),'ð','o'),'ñ','n'),'ò','o'),'ó','o'),'ô','o'),'õ','o'),'ö','o'),'ø','o') AS normal_tag
```

Taken from http://stackoverflow.com/a/16960134/5268893

**Comment by anthonylv** [comment]
Thanks. You might encounter a similar issue with the post_name / slugs in WordPress.

REPLACE(post_name, '\’', '') WHERE post_name LIKE '%\’%';
REPLACE(post_name, '\‘', '') WHERE post_name LIKE '%\‘%';
REPLACE(post_name, '\”', '') WHERE post_name LIKE '%”%';
REPLACE(post_name, '\“', '')  WHERE post_name LIKE '%“%';
